spring.datasource.url=jdbc:h2:mem:ludo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=\
    classpath:db/00-lookup-tables.sql,\
    classpath:db/01-entities-schema.sql
spring.sql.init.data-locations=\
    classpath:db/02-seed-reference-data.sql,\
    classpath:db/03-seed-users.sql
spring.sql.init.continue-on-error=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-port=8090
