
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.usach.hackaton.gpu=DEBUG

spring.config.import=optional:file:./.env.development[.properties]
app.cors.allowed-origin-patterns=http://localhost:3000

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=no-reply@development.local
spring.mail.properties.mail.smtp.from=${spring.mail.username}
spring.mail.properties.mail.from=Ludoteca Dev Local Test <${spring.mail.username}>
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret=${SECRET}
security.jwt.expiration-minutes=60
