
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.usach.hackaton.gpu=DEBUG
app.cors.allowed-origin-patterns=http://localhost:3000

spring.mail.host=localhost
spring.mail.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.username=no-reply@development.local
spring.mail.properties.mail.smtp.from=${spring.mail.username}
spring.mail.properties.mail.from=Ludoteca Dev No-Email <${spring.mail.username}>
app.email.enabled=false

security.jwt.secret=${SECRET:test-security-jwt-secret}
